version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting build process..."
      - echo "Build started on $(date)"

  build:
    commands:
      - echo "Building application..."
      - echo "Build phase completed"

  post_build:
    commands:
      - echo "Build completed successfully on $(date)"
      - echo "SUCCESS: Build finished!"